### ISSUE TITLE
the extract frame triplets train-dataset

### ISSUE THREAD

**Issue by cjcjlin** [alex04072000/CyclicGen#4]
Thanks for your sharing !    
And I wonder that could you provide the extracted frames triplets train-dataset ?
Look forward to your soonest reply.

**Comment by alex04072000** [comment]
Please follow the following steps:

1. download UCF101.rar, and train/test split list

2. extract and rename to UCF101

3. python3 1_move_files.py to split data into train/test

4. parallel -j 12 ./extract_only.sh ::: $( find -name *.avi )

5. python3 2_filter_psnr.py
