### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by lzhangbj** [alex04072000/CyclicGen#6]
Hi, can you give out the link for downloading your training and testing dataset?

**Comment by alex04072000** [comment]
For training dataset, please follow the following steps:
1. download UCF101.rar, and train/test split list
2. extract and rename to UCF101
3. python3 1_move_files.py to split data into train/test
4. parallel -j 12 ./extract_only.sh ::: $( find -name *.avi )
5. python3 2_filter_psnr.py

For testing dataset:

- We use exactly the same as used in [DVF](https://liuziwei7.github.io/projects/VoxelFlow). Please refer to the Datasets section in their website.

**Comment by lzhangbj** [comment]
thank you for the details!
